### ISSUE TITLE
what is  "Mail.tm Password " and "Mail.tm ID"

### ISSUE THREAD

**Issue by maricelase** [f-o/MEGA-Account-Generator#11]
what is  "Mail.tm Password " and "Mail.tm ID"

Fill in the email box and password, But I don't know what I should fill those two things with.

thank

**Comment by f-o** [comment]
Hello,

These two fields are the unique password and unique ID for the mail.tm account, tied to the MEGA account.
Using the password, you can sign in to the inbox on the mail.tm site. In order to access the account, through the Python library, the mail.tm ID is also needed.

These values are only stored, because I figured they could be useful in the future.
As the script is, right now, they are not being used, and you don't need them for "checking" the accounts, using the helper script.

If you're adding accounts to the CSV file manually, you can just type  a dash `-` as filler.
