### ISSUE TITLE
ERROR: Could not get account. Retrying...

### ISSUE THREAD

**Issue by evilsh3ll** [f-o/MEGA-Account-Generator#2]
Hello, I installed latest megatools and your python tools in archlinux, I get this error:
![image](https://github.com/f-o/MEGA-Account-Generator/assets/63223659/841f5624-ed18-45d9-85c5-a16fd9b27037)

**Comment by f-o** [comment]
Since you're trying to generate 200 accounts at a time, you must be rate-limited from the Mail.tm API.
They allow for 8 requests per second per IP. Since we use threading, you're probably hitting close to 200 requests per second.

I would advise you to lower the number of accounts, and run the script multiple times, after a short delay, to get your desired 200 accounts.
It would probably also be a good idea for me to implement proper rate-limiting.

**Comment by f-o** [comment]
This issue has been addressed in the newest release of the script.

If the script cannot get a new Mail.tm account (which was the case for your issue above) it will try for a total of 5 times, with a period of sleep in between.
It will now also properly quit if it fails, and not try endlessly like it did previously.

I'd also like to say that I've taken a step away from Threading, and will not be further going in this direction, as it's only going to cause issues with the rate-limits of Mail.tm.
You can still use threads by explicitly stating this when you run the script, but you will be limited to a maximum of 8 threads at a time (which should be more than enough).

It's okay to use this script to create accounts in bulk, but there's no need to have 200 accounts created "as fast as possible".
By running the script now, with the command `python generate_accounts.py -n 200`, it will still create the 200 accounts, just 1 at a time instead of all at once.
