### ISSUE TITLE
is it wowking rn?

### ISSUE THREAD

**Issue by Gabriel010112** [f-o/MEGA-Account-Generator#3]
not workig on me

**Comment by f-o** [comment]
I just tested the script, and it successfully generated/verified 3 brand new accounts for me.

![image](https://github.com/f-o/MEGA-Account-Generator/assets/30742516/43048d9c-e116-46f6-8f0e-db55a0ec1653)


Are you getting any errors in the script?
How many accounts are you trying to generate?

You may be IP banned from MEGA, which I haven't seen before, but wouldn't be surprised if it was a thing.
Try to hop on a VPN and generate the default 3 accounts.

**Comment by Gabriel010112** [comment]
im gettin these ![Screenshot 2024-05-02 113421](https://github.com/f-o/MEGA-Account-Generator/assets/168632515/de540529-17a3-4af8-90c2-71990f444faf)

**Comment by Gabriel010112** [comment]
oopps, i just updated my python to 3.12 and got it to work, thanks

**Comment by Gabriel010112** [comment]
i keep gettin these 
![image](https://github.com/f-o/MEGA-Account-Generator/assets/168632515/d0644c71-42d1-4c4d-bff4-84af57cb4f83)

**Comment by f-o** [comment]
Hey,

I still got the messages you sent, and while I'm glad that you got it to work in the end, I think the core issue was that you were running the script in ``System32``, which is a privileged area.
You should either move the folder to `Documents`, or another place where you have permission, or run the script as Administrator.

I've also made a lot of new changes to the script since yesterday, so if you can verify that everything is still working, I would be very grateful!

**Comment by Alternatifx** [comment]
in my case this often happen to me, it created email acc but fail to verified the mega acc and no new account are created on .csv as well

![capture-20240510-151515](https://github.com/f-o/MEGA-Account-Generator/assets/36522065/b14ed049-902a-4811-afcf-c579412585f4)
